name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "15 * * * *"
  push:
    branches: [ "main" ]

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v4
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
      - name: setup git config
        run: |
           # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
           git config user.name "GitHub Actions Bot"
           git config user.email "<>"
      - name: commit
        run: |
           # Stage the file, commit and push
           git add -A --force logs/
           git commit -am '[Automated] Update Health Check Logs'
           git push origin main
